version: "3.7"
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true  # allow for debugger
    tty: true         # interaction
    command: bash -c "rm -f tmp/pids/server.pid && bin/rake setup && bin/rake about && bin/rails server -b '0.0.0.0' -p 3000"
    working_dir: /code
    volumes:
      - ..:/code
      - btedata:/data

volumes:
  btedata:
